/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Activity } from './types';

// Local images stored under public/images/activities
const IMAGES = {
  dunas: '/images/activities/dunas.jpg',
  dinner: '/images/activities/dinner.jpg',
  surf: '/images/activities/surf.jpg',
  mtb: '/images/activities/mtb.jpg',
  lobos: '/images/activities/lobos.jpg',
  betancuria: '/images/activities/betancuria.jpg',
  calderon: '/images/activities/calderon.jpg',
  sotavento: '/images/activities/sotavento.jpg',
  cofete: '/images/activities/cofete.jpg',
  snorkel: '/images/activities/snorkel.jpg',
  subGal1: '/images/activities/subGal1.jpg',
  subGal2: '/images/activities/subGal2.jpg',
  subGal3: '/images/activities/subGal3.jpg',
  subGal4: '/images/activities/subGal4.jpg'
};

export const ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    title: 'Sesión de fotos en las Dunas de Corralejo',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Creativo',
    location: 'Dunas de Corralejo',
    shortDescription: 'Captura la esencia minimalista de las dunas blancas de Corralejo.',
    description: 'Las Dunas de Corralejo son un ecosistema único en el mundo, un desierto de arena blanca que se encuentra con el azul turquesa del Atlántico. Este Parque Natural ofrece un lienzo infinito para la creatividad fotográfica, especialmente durante la "hora dorada" cuando las sombras alargadas dibujan relieves espectaculares en la arena.',
    imageUrl: IMAGES.dunas,
    galleryUrls: [IMAGES.dunas, IMAGES.subGal1, IMAGES.subGal2, IMAGES.subGal3],
    lat: 28.698445166949455,
    lng: -13.820905208587647,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_2',
    title: 'Practica surf en las Grandes Playas de Corralejo',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Aventura',
    location: 'Grandes Playas, Corralejo',
    shortDescription: 'Deslízate sobre las famosas olas turquesas del norte de la isla.',
    description: 'Bajo el sol de Corralejo, las Grandes Playas ofrecen condiciones óptimas de viento y olas que las convierten en un enclave legendario para surfistas de todo el mundo. Adecuado tanto para principiantes como para expertos.',
    imageUrl: IMAGES.surf,
    galleryUrls: [IMAGES.surf, IMAGES.subGal3, IMAGES.subGal4],
    lat: 28.70702755309067,
    lng: -13.843811373992983,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_3',
    title: 'Haz snorkel en el Puertito de la Isla de Lobos',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Naturaleza',
    location: 'Puertito de Lobos',
    shortDescription: 'Sumérgete en lagunas de una transparencia inimaginable.',
    description: 'El Puertito de Lobos es un acuario natural de poca profundidad idóneo para bucear entre arrecifes y formaciones de lava volcánica habitadas por una riquísima variedad de fauna marina local.',
    imageUrl: IMAGES.snorkel,
    galleryUrls: [IMAGES.snorkel, IMAGES.lobos],
    lat: 10,
    lng: 85,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_4',
    title: 'Buggies en las Dunas de Corralejo',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Motor',
    location: 'Corralejo',
    shortDescription: 'Siente la adrenalina recorriendo caminos de tierra y dunas.',
    description: 'Explora el paisaje desértico del norte sobre un buggy todoterreno, ascendiendo por senderos rurales con vistas directas al increíble paisaje dunar y al océano.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb, IMAGES.dunas],
    lat: 20,
    lng: 50,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_5',
    title: 'Báñate en la piscina natural de Caleta de Fuste',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Familiar',
    location: 'Caleta de Fuste',
    shortDescription: 'Descubre un charco rocoso protegido de las corrientes marinas.',
    description: 'Una joya escondida esculpida de forma natural en la piedra costera de Caleta de Fuste, ideal para nadar plácidamente en marea alta disfrutando de aguas seguras.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 48,
    lng: 78,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_6',
    title: 'Senderismo a Montaña Roja',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Media',
    type: 'Senderismo',
    location: 'Montaña Roja, Corralejo',
    shortDescription: 'Sube al cono volcánico del norte para disfrutar de vistas celestiales.',
    description: 'La subida a Montaña Roja te recompensará con una vista de 360 grados de todo el norte de Fuerteventura, Lanzarote y la mítica Isla de Lobos. Un sendero de arena y basalto rojizo mágico.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon, IMAGES.subGal4],
    lat: 14,
    lng: 48,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_7',
    title: 'Buceo en Caleta de Fuste',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Acuático',
    location: 'Caleta de Fuste',
    shortDescription: 'Explora la rica biodiversidad del arrecife de Caleta.',
    description: 'Desciende a las profundidades con instructores locales para observar meros, rayas amigables, bancos de sargos y espectaculares paisajes submarinos de roca volcánica basáltica.',
    imageUrl: IMAGES.snorkel,
    galleryUrls: [IMAGES.snorkel],
    lat: 50,
    lng: 82,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_8',
    title: 'Visita el Museo del Queso Majorero',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Antigua',
    shortDescription: 'Aprende los secretos del legendario queso de cabra autóctono.',
    description: 'Ubicado en un histórico molino restaurado en Antigua, el museo interactivo te guiará a través de la ganadería tradicional y te permitirá disfrutar de catas comentadas de quesos premiados.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 55,
    lng: 52,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_9',
    title: 'Visita Betancuria. Antigua capital',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Histórico',
    location: 'Betancuria',
    shortDescription: 'Pasea por el pueblo más antiguo e histórico de Fuerteventura.',
    description: 'Fundada en 1404 por Jean de Béthencourt, su casco histórico está lleno de jardines, calles adoquinadas, casas con balcones de madera tradicionales y la imponente iglesia de Santa María.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria, IMAGES.subGal2],
    lat: 62,
    lng: 34,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_10',
    title: 'Haz la ruta circular del Tindaya',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Senderismo',
    location: 'Montaña de Tindaya',
    shortDescription: 'Rodea la montaña sagrada de los aborígenes mahos.',
    description: 'Descubre los campos áridos de Tindaya rodeando su mítica silueta, considerada un lugar ritual y sagrado por los antiguos habitantes que esculpieron grabados podomorfos singulares.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 38,
    lng: 35,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_11',
    title: 'Ruta Fatbike llanos de Tindaya',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Ciclismo',
    location: 'Tindaya',
    shortDescription: 'Cabalga en bicicleta de ruedas anchas sobre las áridas llanuras arcillosas.',
    description: 'Disfruta de la libertad total que ofrece una Fatbike rodando fácilmente por los extensos llanos desérticos circundantes a la montaña de Tindaya bajo el sol canario.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb],
    lat: 36,
    lng: 31,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_12',
    title: 'Viaja en catamarán al atardecer en Morro-Jable',
    category: 'OCIO',
    duration: '4h aprox.',
    difficulty: 'Baja',
    type: 'Leisure',
    location: 'Morro Jable',
    shortDescription: 'Brinda con champán bajo las luces de la mítica hora dorada del sur.',
    description: 'Relájate a bordo de una embarcación de lujo con barra libre y aperitivos, avistando el relieve costero salvaje de Jandía mientras el Sol se oculta en el horizonte del Océano.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete, IMAGES.subGal1],
    lat: 92,
    lng: 28,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_13',
    title: 'Experiencia con una moto de agua en las playas de Morrojable',
    category: 'DEPORTE',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Acuático',
    location: 'Morro Jable',
    shortDescription: 'Navega a toda velocidad sobre las llanas bahías turquesas del sur.',
    description: 'Alquila modernas motos acuáticas o únete a un safari guiado bordeando los imponentes acantilados dorados que caracterizan Jandía de forma segura.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento],
    lat: 94,
    lng: 32,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_14',
    title: 'Sesión de fotos en Pozo Negro',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Fotografía',
    location: 'Pozo Negro',
    shortDescription: 'Retrata el encanto de un modesto pueblo marinero de rocas negras.',
    description: 'Pozo Negro destaca por sus singulares casitas blancas de pescadores que contrastan con los acantilados basálticos oscuros y la tranquila cala de mar picón negro.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2, IMAGES.subGal4],
    lat: 56,
    lng: 70,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_15',
    title: 'Visita la playa de las Palomitas o Playa del Bajo de la Burra',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Majanicho',
    shortDescription: 'Camina sobre rodolitos de cal que simulan crujientes palomitas de maíz.',
    description: 'Un singular fenómeno de la costa norte donde pequeñas algas coralinas calcificadas llamadas rodolitos cubren la costa simulando miles de palomitas de maíz esparcidas.',
    imageUrl: IMAGES.dunas,
    galleryUrls: [IMAGES.dunas],
    lat: 10,
    lng: 38,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_16',
    title: 'Practica bodyboard en Corralejo, Playa del Moro',
    category: 'DEPORTE',
    duration: '2.5h aprox.',
    difficulty: 'Media',
    type: 'Aventura',
    location: 'Playa del Moro',
    shortDescription: 'Disfruta de las olas orilleras potentes rodeado de dunas.',
    description: 'La Playa del Moro posee una orillera ideal y constante para coger velocidad en bodyboard y divertirte de forma directa en plena naturaleza virgen.',
    imageUrl: IMAGES.surf,
    galleryUrls: [IMAGES.surf],
    lat: 22,
    lng: 64,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_17',
    title: 'Recorre la playa de Sotavento',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Exploración',
    location: 'Sotavento',
    shortDescription: 'Camina descalzo sobre kilómetros de fina arena y aguas bajas turquesas.',
    description: 'La inmensa playa de Sotavento es célebre por su espectacular barrera de arena natural que crea una laguna idílica ideal para pasear sumergiendo los pies.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento, IMAGES.subGal2],
    lat: 80,
    lng: 44,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_18',
    title: 'Toma lecciones de windsurf en Sotavento',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Acuático',
    location: 'Playa de Sotavento',
    shortDescription: 'Iníciate con los vientos alisios más constantes de toda Europa.',
    description: 'Un monitor certificado te guiará desde los primeros pasos montando la vela hasta deslizarte por la laguna de marea transparente sin oleaje fuerte.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento],
    lat: 82,
    lng: 46,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_19',
    title: 'Alucina con las vistas de la playa de Jarubio',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Exploración',
    location: 'Jarubio, Tindaya',
    shortDescription: 'Descubre los acantilados más agrestes y solitarios de la costa oeste.',
    description: 'La playa de Jarubio es un lugar remoto de belleza colosal donde el mar rompe con furia inusitada contra gigantescos acantilados sedimentarios de tonos amarillos.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 44,
    lng: 14,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_20',
    title: 'Come un asado en el restaurante El Horno',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Villaverde',
    shortDescription: 'Prueba la carne de cabrito o cordero asada en tradicional horno de leña.',
    description: 'Uno de los asadores tradicionales de renombre en Villaverde. No te pierdas su afamado cabrito asado tiernísimo maridado con vinos autóctonos canarios.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 22,
    lng: 42,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_21',
    title: 'Visita los Molinos de Villaverde',
    category: 'NATURALEZA',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Histórico',
    location: 'Villaverde',
    shortDescription: 'Fotografía los majestuosos testigos de la molienda del gofio.',
    description: 'Dos icónicos molinos de viento tradicionales situados sobre una loma que rinde tributo a la rica historia agrícola del pueblo cerealista de Villaverde.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 24,
    lng: 46,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_22',
    title: 'Come en el restaurante Casa Marcos',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Villaverde',
    shortDescription: 'Degusta tapas creativas hechas en base a recetas majoreras reinventadas.',
    description: 'Famoso por su pizarra cambiante llena de platos gourmet canarios elaborados con mimo utilizando ingredientes frescos cosechados de su propia huerta.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 25,
    lng: 40,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_23',
    title: 'Ruta por Calderón Hondo',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Senderismo',
    location: 'Lajares',
    shortDescription: 'Contempla la espectacular caldera de un volcán milenario.',
    description: 'Un sendero circular que asciende de forma suave hasta un asombroso balcón colgado sobre un cráter volcánico de gran profundidad rodeado de ardillas morunas.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon, IMAGES.subGal1],
    lat: 18,
    lng: 39,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_24',
    title: 'Báñate en las piscinas naturales de Los Charcos. El Cotillo',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Acuático',
    location: 'El Cotillo',
    shortDescription: 'Sumérgete en pozas de roca volcánica y arena blanca.',
    description: 'Próximas al faro de El Cotillo, estas charcas circundadas por arrecifes naturales son perfectas para darte un baño seguro lejos del fuerte oleaje de la costa oeste.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2, IMAGES.subGal4],
    lat: 22,
    lng: 12,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_25',
    title: 'Contempla un atardecer en El Cotillo',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Romántico',
    location: 'El Cotillo',
    shortDescription: 'Presencia cómo el Sol se hunde lentamente en las profundidades atlánticas.',
    description: 'La costa de El Cotillo tiene fama de albergar las puestas de sol más hermosas, salvajes y espectaculares del archipiélago, tiñendo el relieve costero de colores encendidos.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 24,
    lng: 14,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_26',
    title: 'Come en Secret Garden by Surfescape en Lajares',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Lajares',
    shortDescription: 'Un vergel rodeado de plantas tropicales con gastronomía moderna.',
    description: 'Disfruta de café de especialidad, buddha bowls, zumos de frutas y pizzas artesanales en un ambiente surfero, relajado y de aire internacional muy agradable.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1],
    lat: 26,
    lng: 32,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_27',
    title: 'Visita Majanicho',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Tradicional',
    location: 'Majanicho',
    shortDescription: 'Descubre un refugio marinero donde el tiempo parece haberse detenido.',
    description: 'Majanicho es una pequeña bahía virgen rodeada de casitas tradicionales de piedra seca y pequeñas barcas de pescadores mecidas por las mareas.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 10,
    lng: 32,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_28',
    title: 'Relax en la playa de La Goleta y toma algo en Waikiki Beach Club',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Leisure',
    location: 'Corralejo',
    shortDescription: 'Día de arena fina con música chill-out y cócteles tropicales a pie de playa.',
    description: 'Disfruta de las mansas aguas cristalinas del centro de Corralejo con espectaculares vistas directas a la Isla de Lobos, relajándote con un mojito de coco tradicional.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 15,
    lng: 66,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_29',
    title: 'Come una burger en Savanah Beach',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Corralejo',
    shortDescription: 'Deliciosas hamburguesas gourmet servidas frente a la arena de Corralejo.',
    description: 'Bocados deliciosos con ingredientes locales de primera calidad para recargar las reservas de energía tras una provechosa jornada de surf en las inmediaciones.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 14,
    lng: 68,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_30',
    title: 'Relax en Spa Secret Bahía Real',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Cuidado',
    location: 'Bahia Real, Corralejo',
    shortDescription: 'Consiéntete con un circuito termal de relax absoluto frente al océano.',
    description: 'Un spa de cinco estrellas gran lujo con jacuzzi exterior climatizado, sauna finlandesa y cabinas de masajes con selectos aceites naturales terapéuticos.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 17,
    lng: 70,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_31',
    title: 'Escucha música por la tarde en Sunset Lounge',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Ocio',
    location: 'Corralejo Beach',
    shortDescription: 'Una copa en buena compañía con DJ en vivo frente a las dunas.',
    description: 'Un atardecer con ritmos veraniegos y un ambiente insuperable bañado por la suave brisa alisía del norte del archipiélago.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 19,
    lng: 68,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_32',
    title: 'Deleítate en Playa Esmeralda',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Costa Calma',
    shortDescription: 'Un paraíso virgen de aguas esmeralda resguardado del viento costero.',
    description: 'Playa Esmeralda destaca por sus suaves aguas límpidas rodeadas de dunas bajas, ofreciendo un oasis de total relajación lejos de multitudes ruidosas.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 78,
    lng: 48,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_33',
    title: 'Ruta en Fatbike desde El Roque a la playa de Esquinzo',
    category: 'DEPORTE',
    duration: '3.5h aprox.',
    difficulty: 'Alta',
    type: 'Ciclismo',
    location: 'El Cotillo / Esquinzo',
    shortDescription: 'Bordea indómitos acantilados desérticos de la salvaje vertiente oeste.',
    description: 'Un exigente trazado de puro todoterreno cruzando barrancos costeros y solitarias playas solitarias de arena dorada golpeadas por el Atlántico.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb],
    lat: 28,
    lng: 10,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_34',
    title: 'Sube al Mirador del Vallebrón',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Observación',
    location: 'Vallebrón, La Oliva',
    shortDescription: 'Admira el sobrecogedor relieve erosionado de la sagrada Tindaya.',
    description: 'Situado en una loma a gran altitud, brinda vistas privilegiadas de todo el Valle de Vallebrón, teñido de mágicos ocres y marrones tradicionales.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 32,
    lng: 44,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_35',
    title: 'Párate en Puertito de Los Molinos',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Exploración',
    location: 'Los Molinos',
    shortDescription: 'Una diminuta cala atlántica de bravas olas y cuevas de marea.',
    description: 'Un singular pueblo costero con un puñado de casas y un restaurante local célebre por sus cuevas secretas accesibles solo en grandes bajamares.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos, IMAGES.subGal4],
    lat: 44,
    lng: 11,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_36',
    title: 'Cómete una parrillada en el restaurante El Labrador',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Casillas del Ángel',
    shortDescription: 'Exquisitas carnes asadas a fuego lento acompañadas de verduras.',
    description: 'Un rincón familiar de asados en el corazón rural, célebre por sus abundantes raciones de embutidos y carnes frescas canarias.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 47,
    lng: 48,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_37',
    title: 'Visita el Mirador de Guise y Ayose',
    category: 'NATURALEZA',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Betancuria Mountains',
    shortDescription: 'Dos colosos de bronce custodian la imponente espina dorsal montañosa.',
    description: 'Sácate una foto con los antiguos reyes de la isla que dividieron Fuerteventura en dos reinos. Una ventana incomparable a los valles sinuosos de Betancuria.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria, IMAGES.subGal1],
    lat: 60,
    lng: 32,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_38',
    title: 'Pasea por la playa de arena negra Playa de Gran Valle',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Jandía',
    shortDescription: 'Un sendero costero que desemboca en una solitaria playa azabache.',
    description: 'Una rara playa de arena negra brillante de origen volcánico encerrada entre espectaculares elevaciones y protegida de grandes oleajes.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 86,
    lng: 15,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_39',
    title: 'Snorkel en la playa de La Guirra',
    category: 'DEPORTE',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Acuático',
    location: 'Caleta de Fuste',
    shortDescription: 'Nada junto a tortugas y peces coloridos en arrecifes resguardados.',
    description: 'Playa artificial protegida de las corrientes abiertas por espigones, ideal para disfrutar del snorkel en familia rodeados de multitud de vida marina.',
    imageUrl: IMAGES.snorkel,
    galleryUrls: [IMAGES.snorkel],
    lat: 51,
    lng: 80,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_40',
    title: 'Come en Chiriate Restaurante. Giniginamar',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Giniginamar',
    shortDescription: 'Saborea pescado fresco del día frente a una tranquila bahía pedregosa.',
    description: 'Una taberna familiar donde destaca el arroz con bogavante, calamares sazonados y ensaladas frescas con tomates recolectados en huertos cercanos.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 69,
    lng: 64,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_41',
    title: 'Tómate una copa en Lagoon Beach Club',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Ocio',
    location: 'Sotavento',
    shortDescription: 'Disfruta de cócteles elegantes junto a la hermosa laguna de Sotavento.',
    description: 'Un espectacular espacio moderno al aire libre con música ambiente idóneo para desconectar charlando tras practicar deportes de viento.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2],
    lat: 80,
    lng: 48,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_42',
    title: 'Haz skate por el paseo marítimo de Tarajalejo',
    category: 'DEPORTE',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Skate',
    location: 'Tarajalejo',
    shortDescription: 'Deslízate sobre asfalto liso frente a una inmensa bahía de arena negra.',
    description: 'El largo paseo semi-peatonal de Tarajalejo brinda condiciones perfectas para patinar suavemente disfrutando de la paz sutil del sur del archipiélago.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb],
    lat: 72,
    lng: 56,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_43',
    title: 'Come en Restaurante La Sombra. Betancuria',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Betancuria',
    shortDescription: 'Un oasis arbolado de hamburguesas de autor y ensaladas selectas.',
    description: 'Ubicado en un patio verde empedrado muy bonito en el centro de Betancuria. Excelente opción para refrescarse durante paseos calurosos e históricos.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 64,
    lng: 34,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_44',
    title: 'Snorkel en Playa La Lajita',
    category: 'DEPORTE',
    duration: '2h aprox.',
    difficulty: 'Media',
    type: 'Acuático',
    location: 'La Lajita',
    shortDescription: 'Descubre los impresionantes fondos rocosos habitados de un enclave costero.',
    description: 'Sumerge las gafas para nadar entre espectaculares formaciones sedimentarias en una playa negra virgen frecuentada por garzas reales costeras.',
    imageUrl: IMAGES.snorkel,
    galleryUrls: [IMAGES.snorkel],
    lat: 76,
    lng: 43,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_45',
    title: 'Visita el Jardín Botánico de Fuerteventura',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Botánica',
    location: 'La Lajita',
    shortDescription: 'La colección más grande de cactus y suculentas de Canarias.',
    description: 'Un remanso de paz con miles de especies desérticas endémicas de África, América y Canarias cuidadas con mimo en un palmeral inmenso.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 76,
    lng: 46,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_46',
    title: 'Haz una parada en Restaurante Mirador Sotavento',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Costa Calma',
    shortDescription: 'Saborea platos abundantes tradicionales con la mejor panorámica marina.',
    description: 'Ubicado en una loma elevada, permite otear cómodamente los kilométricos bancos de arena de Sotavento mientras cenas carnes tiernas asadas.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 78,
    lng: 49,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_47',
    title: 'Pasa una mañana en Oasis Wildlife',
    category: 'OCIO',
    duration: '5h aprox.',
    difficulty: 'Baja',
    type: 'Familiar',
    location: 'La Lajita',
    shortDescription: 'Un oasis de naturaleza tropical con fauna rescatada y jardines.',
    description: 'Diviértete en un enorme parque interactivo, aprende todo sobre alimentación de jirafas y tótems naturales del continente africano.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 75,
    lng: 44,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_48',
    title: 'Pasea por el palmeral de Costa Calma',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Costa Calma',
    shortDescription: 'Cruce verde en medio del desierto lleno de palmeras canarias.',
    description: 'Una magnífica mancha forestal artificial regada con aguas depuradas que conforma un hermoso corredor verde de alta oxigenación.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 79,
    lng: 46,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_49',
    title: 'Come en el Tucán Grill Bar',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Morro Jable',
    shortDescription: 'Las mejores brochetas de carne y flanes artesanales tradicionales.',
    description: 'Un rincón rústico en el sur de la isla bien valorado por surfistas y lugareños por igual debido a su parrilla de carbón y jugos naturales.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 90,
    lng: 32,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_50',
    title: 'Relájate en la playa del Muellito',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Leisure',
    location: 'Morro Jable',
    shortDescription: 'Día de baño seguro en aguas de un azul celeste en el casco histórico.',
    description: 'La antigua playa urbana dorada del pueblo pesquero de Morro Jable, resguardada de vientos y con una oferta gastronómica inmejorable.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 92,
    lng: 30,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_51',
    title: 'Completa la Senda de los Cetáceos',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Salinas del Carmen',
    shortDescription: 'Admira un verdadero esqueleto gigante de rorcual junto al océano.',
    description: 'Un precioso museo al aire libre que rinde tributo a las ballenas y delfines que habitan el corredor biológico atlántico canario.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 53,
    lng: 78,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_52',
    title: 'Conoce el aceite majorero y los olivos de Teguerey',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Tradicional',
    location: 'Teguerey, Antigua',
    shortDescription: 'Aprende los procesos de elaboración de oliva extra virgen desértico.',
    description: 'Ruta guiada por extensos bancales de olivos regados gota a gota para extraer un aceite majorero con premios de prestigio internacional.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 54,
    lng: 54,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_53',
    title: 'Visita el Arco de Peñitas',
    category: 'NATURALEZA',
    duration: '3.5h aprox.',
    difficulty: 'Alta',
    type: 'Senderismo',
    location: 'Vega de Río Palmas',
    shortDescription: 'Un espectacular arco pétreo natural labrado en granito jurásico.',
    description: 'El barranco de las Peñitas resguarda una de las formaciones geológicas de granito más antiguas de Canarias, ideal para aventureros intrépidos.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria, IMAGES.subGal4],
    lat: 65,
    lng: 26,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_54',
    title: 'Báñate en la playa de Ajuy',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Media',
    type: 'Bravío',
    location: 'Ajuy',
    shortDescription: 'Siente la inmensidad de una playa de pura arena oscura basáltica.',
    description: 'Es célebre por su inmensa arena negra y acantilados que resguardan fósiles antiguos. Se debe nadar con extrema cautela por las corrientes costeras bravas.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 64,
    lng: 15,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_55',
    title: 'Camina de Ajuy al Arco del Jurado',
    category: 'NATURALEZA',
    duration: '4h aprox.',
    difficulty: 'Alta',
    type: 'Senderismo',
    location: 'Ajuy',
    shortDescription: 'Camina entre dunas fósiles hasta un colosal acantilado perforado.',
    description: 'Una exigente travesía bordeando la escarpada vertiente oeste para admirar el gigantesco túnel de roca esculpido por el implacable mar de Ajuy.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 66,
    lng: 13,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_56',
    title: 'Disfruta de un cocktail en Atlántico Lounge',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Coctelería',
    location: 'Corralejo',
    shortDescription: 'Vistas panorámicas hermosas de Lobos mientras disfrutas de licores.',
    description: 'Una de las terrazas más de moda en Corralejo, ideal para acabar la tarde tapeando de forma lujosa y sofisticada.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2],
    lat: 13,
    lng: 71,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_57',
    title: 'Juega al mini golf en Caleta de Fuste',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Familiar',
    location: 'Caleta de Fuste',
    shortDescription: 'Un divertido recorrido temático entre palmeras y riachuelos artificiosos.',
    description: 'Ideal para pasar una tarde familiar agradable completando ocurrentes hoyos de destreza bajo un sol espléndido constante.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 49,
    lng: 78,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_58',
    title: 'Contempla una puesta de sol en Ajuy',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Fotografía',
    location: 'Ajuy',
    shortDescription: 'Derrite la mirada con el resplandor de puestas de sol en el oeste.',
    description: 'Los sedimentos y acantilados áridos de Ajuy reflejan las luces doradas tornándose cobrizos, creando una sobrecogedora estampa romántica.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 63,
    lng: 14,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_59',
    title: 'Visita el Faro Punta de Jandía',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Monumento',
    location: 'Punta de Jandía',
    shortDescription: 'La solitaria punta más meridional batida por corrientes feroces.',
    description: 'En el confín sur de Fuerteventura, el altivo faro vigila el fin de la isla flanqueado por calas volcánicas desiertas.',
    imageUrl: IMAGES.subGal4,
    galleryUrls: [IMAGES.subGal4],
    lat: 91,
    lng: 10,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_60',
    title: 'Fotografíate en la Cueva de los Ojos',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Alta',
    type: 'Fotografía',
    location: 'Playa de los Ojos',
    shortDescription: 'Baja a recovecos secretos tallados en roca caliza dorada.',
    description: 'Dos sugerentes orificios perforados en el acantilado que enmarcan la grandiosa playa solitaria del sur como verdaderos ojos pétreos.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2],
    lat: 89,
    lng: 12,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_61',
    title: 'Conquista el Mirador de Cofete',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Media',
    type: 'Observación',
    location: 'Degollada de Agua Oveja',
    shortDescription: 'El balcón más imponente y sobrecogedor de toda Canarias.',
    description: 'Una parada obligada al coronar la montaña tras un sendero pedregoso, desde donde los 12 km de mar bravo de Cofete te dejarán sin resuello.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete, IMAGES.subGal1],
    lat: 87,
    lng: 18,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_62',
    title: 'Explora Casa Winter',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Misterio',
    location: 'Cofete',
    shortDescription: 'Una enigmática mansión alemana llena de leyendas de la II Guerra Mundial.',
    description: 'Construida por el ingeniero Gustav Winter en un enclave totalmente inaccesible. Guarda pasadizos, misteriosas leyendas sobre submarinos y búnkeres.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2],
    lat: 88,
    lng: 16,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_63',
    title: 'Contempla la playa de Sotavento desde el Mirador del Salmo',
    category: 'NATURALEZA',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Observación',
    location: 'El Salmo',
    shortDescription: 'Arroja luz sobre la más famosa lengua de arena blanca atlántica.',
    description: 'Vistas inmejorables de la barra de arena y lagunas cambiantes por las mareas. El azul turquesa se despliega en mil tonalidades gloriosas.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento],
    lat: 84,
    lng: 40,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_64',
    title: 'Relájate en el restaurante Costa Beach',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Costa Calma',
    shortDescription: 'Saborea platos ligeros marineros literalmente sobre la arena fina.',
    description: 'Un coqueto chiringuito con ensaladas frescas tropicales, pescado empanado crujiente y cafés frente a las olas de marea de Costa Calma.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 80,
    lng: 46,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_65',
    title: 'Disfruta de un paseo a caballo por El Cotillo',
    category: 'DEPORTE',
    duration: '3h aprox.',
    difficulty: 'Media',
    type: 'Animal',
    location: 'El Cotillo',
    shortDescription: 'Cabalga majestuosamente bordeando acantilados con brisa salada.',
    description: 'Una experiencia inolvidable con guías expertos que te llevarán por agrestes senderos norteños con el atardecer como telón de fondo.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 26,
    lng: 16,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_66',
    title: 'Come una parrillada en Humo BBQ. Tequital',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Tequital',
    shortDescription: 'Genuino ahumado al estilo americano con maderas finas y carnes canarias.',
    description: 'Una propuesta innovadora de asados en un paraje de secano. Exquisitos brisket de ternera tierna desmenuzable y costillas jugosas glaseadas.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 61,
    lng: 60,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_67',
    title: 'Visita Verdeaurora Bio Farm y su plantación de Aloe Vera',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Tenicosquey',
    shortDescription: 'Aprende los procesos de extracción del aloe vera ecológico puro.',
    description: 'Visita una preciosa explotacion biológica certificada en un remanso árido tradicional, conociendo además su plantación de olivos centenarios.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 58,
    lng: 56,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_68',
    title: 'Avistamiento de delfines en Morro Jable',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'Morro Jable Port',
    shortDescription: 'Embarca en una lancha rápida para avistar cetáceos en libertad.',
    description: 'Las profundidades de Jandía son un santuario marino de biodiversidad. Sorpréndete viendo jugar familias enteras de calderones y delfines listados.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 91,
    lng: 26,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_69',
    title: 'Visita el Faro del Tostón',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Exploración',
    location: 'El Cotillo',
    shortDescription: 'El imponente faro norteño que delimita el estratégico estrecho de la Bocaina.',
    description: 'Un singular faro de rayas blancas y rojas que resguarda un pequeño museo sobre la pesca artesanal mayorera tradicional canaria.',
    imageUrl: IMAGES.subGal4,
    galleryUrls: [IMAGES.subGal4],
    lat: 20,
    lng: 10,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_70',
    title: 'Báñate en la playa de La Concha, El Cotillo',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Eco',
    location: 'El Cotillo',
    shortDescription: 'Una idílica media luna de fina arena clara libre de oleaje fuerte.',
    description: 'La playa estrella de El Cotillo para pasar el día en familia. Sus arrecifes naturales forman un espigón de aguas mansas turquesas perfectas.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 21,
    lng: 12,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_71',
    title: 'Tómate algo en The Roof Chill Out',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Ocio',
    location: 'Morro Jable',
    shortDescription: 'Copas de autor con música tranquila brasileña alzadas sobre el casco urbano.',
    description: 'Una azotea chill-out de estilo colonial con luces guirnalda y una vista inmejorable del viejo muellito de Morro Jable.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 92,
    lng: 29,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_72',
    title: 'Visita el Castillo del Tostón y los hornos de cal, El Cotillo',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Histórico',
    location: 'El Cotillo',
    shortDescription: 'Fortín defensivo circular del siglo XVIII contra piratas berberiscos.',
    description: 'Bordea la histórica torre de defensa pétrea contemplando los antiguos hornos que exportaban cal de alta calidad a todos los rincones europeos.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 23,
    lng: 15,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_73',
    title: 'Pasa el día en la playa del Castillo, El Cotillo',
    category: 'OCIO',
    duration: '4h aprox.',
    difficulty: 'Baja',
    type: 'Leisure',
    location: 'El Cotillo Beaches',
    shortDescription: 'Kilómetros de doradas orillas idóneas para caminatas de relax.',
    description: 'La playa salvaje meridional de El Cotillo, famosa por sus potentes olas, formaciones rocosas erosionadas y dunas que invitan al total esparcimiento.',
    imageUrl: IMAGES.cofete,
    galleryUrls: [IMAGES.cofete],
    lat: 25,
    lng: 13,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_74',
    title: 'Toma algo en Uga Uga Bar',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Ocio',
    location: 'Lajares',
    shortDescription: 'Un bar bohemio tradicional cubierto de tablas de surf de época.',
    description: 'El punto de encuentro clásico de surfistas de Lajares por su excelente música rock setentera, cervezas bien frías canarias y tapas de quesos locales.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 25,
    lng: 33,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_75',
    title: 'Un grill chulo. Poco Loco',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Costa Calma',
    shortDescription: 'Variedad de carnes exóticas, fajitas y cortes ahumados riquísimos.',
    description: 'Un asador de ambiente divertido y ocurrentemente decorado, con fajitas y brochetas regadas con cerveza artesanal costera fresca.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 79,
    lng: 48,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_76',
    title: 'Acaba una tarde en Rock Café - Corralejo',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Ocio',
    location: 'Corralejo',
    shortDescription: 'Música rock en directo, hamburguesas y billares en el corazón nocturno.',
    description: 'Un mítico local de Corralejo con un ambiente inmejorable de música rock interpretada por músicos de jazz-rock de gran talento.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 14,
    lng: 64,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_77',
    title: 'Ruta Fatbikes por la costa del Cotillo a Esquinzo',
    category: 'DEPORTE',
    duration: '4h aprox.',
    difficulty: 'Alta',
    type: 'Ciclismo',
    location: 'El Cotillo',
    shortDescription: 'Cabalga dunas fósiles y pedregales áridos y costeros de corte andino.',
    description: 'Una exigente travesía que te desafía a rodar entre senderos donde la piedra beige sedimentaria brilla bajo el abrasador sol del oeste canario.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb],
    lat: 27,
    lng: 11,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_78',
    title: 'Carnaval Blanco de Tetir en Marzo',
    category: 'OCIO',
    duration: '6h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Tetir',
    shortDescription: 'Una divertidísima batalla campal de polvos de talco vistiéndose de gala blanca.',
    description: 'La fiesta tradicional más esperada de Tetir. Familias enteras se visten de lino blanco indiano danzando al ritmo de sones tradicionales de Cuba.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 39,
    lng: 47,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_79',
    title: 'Recorre en skate el paseo de Morro Jable',
    category: 'DEPORTE',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Skate',
    location: 'Morro Jable Promenade',
    shortDescription: 'Disfruta de carriles de skate amplios que flanquean arenales inmensos.',
    description: 'Un extenso bulevar liso que une el palmeral costero con las zonas comerciales de Morro Jable. Sencillamente relajante y deportivo canario.',
    imageUrl: IMAGES.mtb,
    galleryUrls: [IMAGES.mtb],
    lat: 91,
    lng: 32,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_80',
    title: 'Cómete una paella en el Patai Beach Corralejo',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Patai Beach, Corralejo',
    shortDescription: 'Arroz al sarmiento con mariscos suculentos en la fina terraza playera.',
    description: 'Un popular arroz caldoso elaborado con calamares negros locales maridado con tintos canarios procedentes de parcelas volcánicas de alto relieve.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 13,
    lng: 65,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_81',
    title: 'Pasa el día en el parque acuático de Corralejo',
    category: 'OCIO',
    duration: '5h aprox.',
    difficulty: 'Baja',
    type: 'Familiar',
    location: 'Acua Water Park, Corralejo',
    shortDescription: 'Toboganes vertiginosos, jacuzzis y piscinas de olas refrescantes.',
    description: 'El único parque acuático de Fuerteventura con ríos rápidos divertidísimos y pistas blandas ideales para descargar adrenalina en familia.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 15,
    lng: 61,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_82',
    title: 'Coge tu dron y vuela por los acantilados de Ajuy',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Fotografía',
    location: 'Ajuy Cliffline',
    shortDescription: 'Graba espectaculares tomas cenitales de la espuma marina en piedra negra.',
    description: 'Disfruta de perspectivas aéreas majestuosas del poder de erosión marino cincelando dunas fósiles basálticas de más de cien millones de años.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 64,
    lng: 13,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_83',
    title: 'Haz shopping en el centro comercial de Puerto del Rosario',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Leisure',
    location: 'Puerto del Rosario',
    shortDescription: 'Exclusivas marcas náuticas y de moda playera tradicionales de Canarias.',
    description: 'Disfruta de una tarde de compras relajantes en el centro comercial cubierto Las Rotondas antes de degustar suculentos helados de mojo dulce locales.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 41,
    lng: 60,
    rating: 4.5,
    xpAward: 50
  },
  {
    id: 'act_84',
    title: 'Escucha una Jam Session en Pub La Tierra',
    category: 'OCIO',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Puerto del Rosario',
    shortDescription: 'Un local bohemio y alternativo rústico con jazz y blues improvisado.',
    description: 'Pub de época de atmósfera embriagadora enraizado en un histórico caserón colonial canario restaurado con mimo por músicos locales.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 42,
    lng: 58,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_85',
    title: 'Visita el centro de interpretación Poblado de la Atalayita',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Histórico',
    location: 'Pozo Negro Valley',
    shortDescription: 'Camina entre infinidad de ruinas de piedra de los antiguos aborígenes mahos.',
    description: 'Estudia de primera mano cómo vivían los antiguos de la isla bajo campos de lava volcánica erigiendo cuevas basálticas semicubiertas muy seguras.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 57,
    lng: 68,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_86',
    title: 'Visita el Molino de Tiscamanita',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Histórico',
    location: 'Tiscamanita',
    shortDescription: 'Arroja luz sobre la molida de gofio y el uso de tracción animal.',
    description: 'Un precioso y antiguo molino rodeado de aperos labrador que narra el esfuerzo rural majorero tradicional para subsistir moliendo grano.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 61,
    lng: 52,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_87',
    title: 'Acude a la romería de la Virgen de la Peña',
    category: 'OCIO',
    duration: '5h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Vega de Río Palmas',
    shortDescription: 'La peregrinación patronal más solemne y folclórica en septiembre.',
    description: 'Únete a miles peregrinos que caminan con trajes típicos canarios entonando coplas con timples en honor a la bella virgen de madera tallada de La Peña.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 67,
    lng: 28,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_88',
    title: 'Acude al mercado de artesanía de Lajares el sábado',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Tradicional',
    location: 'Lajares Square',
    shortDescription: 'Adquiere calados tradicionales de hilo bordados por sabios ancianos.',
    description: 'Bajo sombrillas de lino rústico, descubre joyas de plata talladas a mano de conchas marinas y selecto queso majorero madurado artesanal.',
    imageUrl: IMAGES.dinner,
    galleryUrls: [IMAGES.dinner],
    lat: 25,
    lng: 31,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_89',
    title: 'Recorre las calles blancas de Pájara',
    category: 'NATURALEZA',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Monumento',
    location: 'Pájara Town',
    shortDescription: 'Fotografía la fachada azteca de la histórica iglesia barroca.',
    description: 'Pajára posee una iglesia de gran renombre con tallas mesoamericanas de jaguares y soles grabados en roca basáltica negra de gran belleza.',
    imageUrl: IMAGES.betancuria,
    galleryUrls: [IMAGES.betancuria],
    lat: 70,
    lng: 26,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_90',
    title: 'Descubre las esculturas de Puerto del Rosario',
    category: 'OCIO',
    duration: '2h aprox.',
    difficulty: 'Baja',
    type: 'Cultural',
    location: 'Puerto del Rosario',
    shortDescription: 'Un monumental museo urbano que expone cientos esculturas públicas.',
    description: 'Camina por el paseo portuario admirando grandes bloques pétreos de caracoles hercúleos tallados de forma sublime por artistas de vanguardia.',
    imageUrl: IMAGES.lobos,
    galleryUrls: [IMAGES.lobos],
    lat: 42,
    lng: 61,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_91',
    title: 'Sube al Monte Tindaya',
    category: 'NATURALEZA',
    duration: '3.5h aprox.',
    difficulty: 'Alta',
    type: 'Senderismo',
    location: 'Tindaya Peak',
    shortDescription: 'Bordea senderos sagrados arqueológicos autorizados en la montaña.',
    description: 'Consigue la autorización del cabildo para recorrer las laderas volcánicas de roca traquita con grabados de formas de pie talladas hace siglos.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 38,
    lng: 36,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_92',
    title: 'Descubre la Cueva de Villaverde',
    category: 'NATURALEZA',
    duration: '2.5h aprox.',
    difficulty: 'Media',
    type: 'Histórico',
    location: 'Villaverde Caves',
    shortDescription: 'Un asombroso tubo volcánico subterráneo de la era antes de la conquista.',
    description: 'Explora galerías basálticas sepultadas bajo campos áridos que sirvieron de refugio y silos alimentarios tradicionales aborígenes.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 23,
    lng: 44,
    rating: 4.7,
    xpAward: 50
  },
  {
    id: 'act_93',
    title: 'Toma una clase de E-Foil',
    category: 'DEPORTE',
    duration: '2h aprox.',
    difficulty: 'Media',
    type: 'Acuático',
    location: 'Corralejo Lagoon',
    shortDescription: 'Vuela literalmente por encima del agua con tablas de hidropatín eléctrico.',
    description: 'Siente la increíble ingravidez de surfear flotando sobre el agua gracias a las modernas tablas propulsadas silenciosamente mediante batería segura.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento],
    lat: 16,
    lng: 64,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_94',
    title: 'Kayak en Isla de Lobos',
    category: 'DEPORTE',
    duration: '3.5h aprox.',
    difficulty: 'Media',
    type: 'Aventura',
    location: 'El Río Strait / Lobos',
    shortDescription: 'Cruza el idílico brazo marino remando entre aguas cristalinas profundas.',
    description: 'Una travesía inolvidable partiendo de bandera blanca en Corralejo sorteando aguas del canal bajo una perspectiva marina espectacular.',
    imageUrl: IMAGES.sotavento,
    galleryUrls: [IMAGES.sotavento],
    lat: 11,
    lng: 76,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_95',
    title: 'Asiste al Festival de Cometas en Octubre',
    category: 'OCIO',
    duration: '4h aprox.',
    difficulty: 'Baja',
    type: 'Tradicional',
    location: 'Grandes Playas de Corralejo',
    shortDescription: 'Cientos cometas gigantes de colores tiñen el impoluto cielo costero.',
    description: 'Un asombroso espectáculo al aire libre de gran renombre mundial que congrega pilotos acrobáticos rodeando las inmensas dunas del norte canario.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1, IMAGES.subGal2],
    lat: 18,
    lng: 58,
    rating: 4.9,
    xpAward: 50
  },
  {
    id: 'act_96',
    title: 'Ruta senderismo de Costa Calma a La Pared',
    category: 'DEPORTE',
    duration: '5h aprox.',
    difficulty: 'Alta',
    type: 'Senderismo',
    location: 'El Istmo de Jandía',
    shortDescription: 'Cruza a pie el deshabitado cuello de botella arenoso de la isla.',
    description: 'Un sendero exigente que te lleva desde calas tranquilas del este a impetuosos acantilados de un mar embravecido de dunas sedimentarias del oeste.',
    imageUrl: IMAGES.calderon,
    galleryUrls: [IMAGES.calderon],
    lat: 77,
    lng: 35,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_97',
    title: 'Excursión en camello en Lajares',
    category: 'OCIO',
    duration: '2.5h aprox.',
    difficulty: 'Baja',
    type: 'Familiar',
    location: 'Lajares Camel Park',
    shortDescription: 'Cabalga de forma pausada sobre dunas desérticas subido en monturas.',
    description: 'Paseo guiado a lomo del dromedario tradicional, rindiendo tributo al histórico y antiguo transporte rural en zonas de secano desértico majorero.',
    imageUrl: IMAGES.subGal1,
    galleryUrls: [IMAGES.subGal1],
    lat: 25,
    lng: 29,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_98',
    title: 'Relájate en Coco Café',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Gastronomía',
    location: 'Lajares',
    shortDescription: 'Deliciosos zumos tropicales, batidos de frutas y tartas veganas orgánicas.',
    description: 'Un coqueto rincón surfero con música étnica de gran paz interior, ideal para refrescarse durante paseos pedregosos tradicionales.',
    imageUrl: IMAGES.subGal3,
    galleryUrls: [IMAGES.subGal3],
    lat: 24,
    lng: 32,
    rating: 4.6,
    xpAward: 50
  },
  {
    id: 'act_99',
    title: 'Pásate por "Las Bohemias del Amor"',
    category: 'OCIO',
    duration: '1.5h aprox.',
    difficulty: 'Baja',
    type: 'Exploración',
    location: 'El Cotillo Cliffs',
    shortDescription: 'Un singular rincón romántico esculpido por poetas frente al océano.',
    description: 'Un curioso abrigo costero de piedra volcánica donde amantes grabaron versos sentimentales de cara al infinito bravío mar del oeste costero canario.',
    imageUrl: IMAGES.subGal2,
    galleryUrls: [IMAGES.subGal2],
    lat: 26,
    lng: 13,
    rating: 4.8,
    xpAward: 50
  },
  {
    id: 'act_100',
    title: 'Visita el Faro de la Entallada',
    category: 'NATURALEZA',
    duration: '3h aprox.',
    difficulty: 'Baja',
    type: 'Observación',
    location: 'Las Playas, Tuineje',
    shortDescription: 'Un colosal balcón colgado sobre acantilados cuchillo del este.',
    description: 'Construido con sillares rojizos de cantería volcánica. Su espectacular mirador colgante elevado es el punto físico más cercano al continente africano de toda Canarias.',
    imageUrl: IMAGES.subGal4,
    galleryUrls: [IMAGES.subGal4],
    lat: 65,
    lng: 78,
    rating: 4.9,
    xpAward: 50
  }
];

export const AVATARS = [
  // 5 Masculinos
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Jack&backgroundColor=b6e3f4',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Oliver&backgroundColor=c0aede',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Leo&backgroundColor=d1f4ff',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Charlie&backgroundColor=ffd5dc',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Felix&backgroundColor=ffdfbf',
  // 5 Femeninos
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Sophia&backgroundColor=b6e3f4',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Aneka&backgroundColor=c0aede',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Lily&backgroundColor=d1f4ff',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Zoe&backgroundColor=ffd5dc',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Maya&backgroundColor=ffdfbf'
];
